services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: react-flask-app-server
    ports:
      - "5000:5000"
  worker:
    image: react-flask-app-server
    command: python3 -u manage.py run_worker
    depends_on:
      - server
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: react-flask-app-client
    ports:
      - "3000:80"