services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-flask-app
    ports:
      - "3000:3000"
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: react-flask-app-redis
