services:
  master:
    build:
      context: .
      dockerfile: Dockerfile.master
    image: react-flask-app
    ports:
      - "3000:3000"
    env_file:
      - ./.env
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: react-flask-app-redis
    env_file:
      - ./.env