services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-flask-app
    ports:
      - "3000:3000"
    env_file:
      - ./.env
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: react-flask-app-redis
    env_file:
      - ./.env
  webhook:
    build:
      context: .
      dockerfile: Dockerfile.webhook
    image: react-flask-app-webhook
    ports:
      - 8888:8888
    env_file:
      - ./.env