services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: react-flask-app-server
    command: gunicorn --bind 0.0.0.0:5000 --access-logfile - --error-logfile - manage:app
    ports:
      - "5000:5000"
    env_file:
      - ./.env
  worker:
    image: react-flask-app-server
    command: python3 -u manage.py run_worker
    depends_on:
      - server
    env_file:
      - ./.env
  webhook:
    build:
      context: .
      dockerfile: Dockerfile.webhook
    image: react-flask-app-webhook
    ports:
      - 8888:8888
    env_file:
      - ./.env
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: react-flask-app-client
    ports:
      - "3000:80"