services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: react-flask-app-server
    ports:
      - "5000:5000"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: react-flask-app-client
    ports:
      - "3000:80"