services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: react-flask-app-server
    command: gunicorn --bind 0.0.0.0:5000 --access-logfile - --error-logfile - manage:app
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    environment:
      - WEBHOOK_ENDPOINT=http://server:5000/webhook
      - API_PORT=5000
  worker:
    image: react-flask-app-server
    command: python3 -u manage.py run_worker
    env_file:
      - ./.env
    environment:
      - WEBHOOK_ENDPOINT=http://server:5000/webhook
    depends_on:
      - server
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: react-flask-app-client
    ports:
      - "3000:80"