version: '3.8'

services:

  master:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: master
    container_name: master
    ports:
      - 5004:5000
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://celebaltartan:password@celebal-tartan-db.mysql.database.azure.com:3306/flaskdevdb?ssl_ca=./app/database/DigiCertGlobalRootCA.crt.pem
      - SECRET_KEY="d68653675379485599f7876a3b469a57"
      - REDIS_HOSTNAME="CelebalTartan.redis.cache.windows.net"
      - REDIS_PASSWORD="gKtowrl1NGs7PBbsga0iYBceuaqE4jYStAzCaMDgPa8="
      - APP_FOLDER=/home/app/server/
      - PORT=5000
    restart: always


  worker:
    image: master
    command: python3 -u manage.py run_worker
    environment:
      - REDIS_HOSTNAME="CelebalTartan.redis.cache.windows.net"
      - REDIS_PASSWORD="gKtowrl1NGs7PBbsga0iYBceuaqE4jYStAzCaMDgPa8="
      - APP_FOLDER=/home/app/server/
    depends_on:
      - master


  webhook:
    build: ./webhook
    image: webhook
    container_name: webhook
    ports:
      - 8888:8888
    environment:
      - WEBHOOK_ENDPOINT=http://webhook:8888
