version: '3.8'

services:

  master:
    build: .
    image: master
    container_name: master
    ports:
      - 5004:5000
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.dev

  worker:
    image: master
    command: python3 -u manage.py run_worker
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - master

  webhook:
    build: ./webhook
    image: webhook
    container_name: webhook
    ports:
      - 8888:8888
    env_file:
      - ./.env.dev