version: '3.8'

services:

  master:
    build:
      context: .
      dockerfile: Dockerfile
    image: master
    container_name: master
    volumes:
      - app-volume:/usr/src/app
    ports:
      - 5004:5000
    env_file:
      - ./.env.dev
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://username:password@dbserver/flaskDB
    links:
      - mysql:dbserver
    restart: always
    depends_on:
      - mysql


  worker:
    image: master
    command: python3 -u manage.py run_worker
    volumes:
      - app-volume:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - master


  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    volumes:
      - app-volume:/usr/src/app
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=flaskDB
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
    restart: always


volumes:
  app-volume:
    name: app-volume-001