version: '3.8'

services:

  master:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: master
    container_name: master
    ports:
      - 5004:5000
    env_file:
      - ./.env.dev
    restart: always


  worker:
    image: master
    command: python3 -u manage.py run_worker
    env_file:
      - ./.env.dev
    depends_on:
      - master