version: '3.8'

services:

  master:
    build:
      context: .
      dockerfile: Dockerfile
    image: master
    container_name: master
    volumes:
      - app-volume:/usr/src/app
    ports:
      - 5004:5000
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://username:password@dbserver/flaskDB
      - SECRET_KEY=d68653675379485599f7876a3b469a57
      - AZURE_REDIS_HOST=CelebalTartan.redis.cache.windows.net
      - AZURE_REDIS_PASSWORD=gKtowrl1NGs7PBbsga0iYBceuaqE4jYStAzCaMDgPa8=
      - AZURE_REDIS_PORT=6380
      - PORT=5000
    links:
      - mysql:dbserver
    restart: always
    depends_on:
      - mysql


  worker:
    image: master
    command: python3 -u manage.py run_worker
    volumes:
      - app-volume:/usr/src/app
    environment:
      - AZURE_REDIS_HOST=CelebalTartan.redis.cache.windows.net
      - AZURE_REDIS_PASSWORD=gKtowrl1NGs7PBbsga0iYBceuaqE4jYStAzCaMDgPa8=
      - AZURE_REDIS_PORT=6380
    depends_on:
      - master


  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    volumes:
      - app-volume:/usr/src/app
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=flaskDB
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
    restart: always


  webhook:
    build: ./webhook
    image: webhook
    container_name: webhook
    ports:
      - 8888:8888
    environment:
      - WEBHOOK_ENDPOINT=http://webhook:8888

volumes:
  app-volume:
    name: app-volume-001