name: Trigger auto deployment for containerappcelebaltartan

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ creating_single_container_deployment ]
    paths:
    - '/**'
    - '.github/workflows/containerappcelebaltartan-AutoDeployTrigger-62926b5d-5e79-4750-a86b-1d1ee1ca4cf1.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acrtartanuat.azurecr.io
          username: ${{ secrets.CONTAINERAPPCELEBALTARTAN_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPCELEBALTARTAN_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acrtartanuat.azurecr.io/tartan_payslip_training/master:${{ github.sha }}
          file: Dockerfile.combo
          context: Dockerfile.combo


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPPCELEBALTARTAN_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n containerappcelebaltartan -g PayslipTrainingUAT --server acrtartanuat.azurecr.io --username  ${{ secrets.CONTAINERAPPCELEBALTARTAN_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPCELEBALTARTAN_REGISTRY_PASSWORD }}
            az containerapp update -n containerappcelebaltartan -g PayslipTrainingUAT --image acrtartanuat.azurecr.io/tartan_payslip_training/master:${{ github.sha }}
