name: Trigger auto deployment for tartancontainerapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ creating_single_container_deployment ]
    paths:
    - '**'
    - '.github/workflows/containerapp-AutoDeployTrigger.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acrtartanuat.azurecr.io
          username: ${{ secrets.TARTANCONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.TARTANCONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acrtartanuat.azurecr.io/tartan_payslip_training/master:${{ github.sha }}
          file: ./Dockerfile.master
          context: ./

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acrtartanuat.azurecr.io/tartan_payslip_training/worker:${{ github.sha }}
          file: ./Dockerfile.worker
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TARTANCONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n tartancontainerapp -g UAT --server acrtartanuat.azurecr.io --username  ${{ secrets.TARTANCONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.TARTANCONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n tartancontainerapp -g UAT --image acrtartanuat.azurecr.io/tartan_payslip_training/master:${{ github.sha }} --container-name master


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n tartancontainerapp -g UAT --server acrtartanuat.azurecr.io --username  ${{ secrets.TARTANCONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.TARTANCONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n tartancontainerapp -g UAT --image acrtartanuat.azurecr.io/tartan_payslip_training/worker:${{ github.sha }} --container-name worker
